backend:
  name: github
  repo: keefeere/keefeere.me
  branch: main
  auth:
    client_id: Ov23litDBSEPpFUzxqI6

media_folder: "static/uploads"
public_folder: "/uploads"

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          # original format
          format: webp # new format, only `webp` is supported
          quality: 85 # default: 85
          width: 1024 # default: original size
          height: 1024 # default: original size
        svg:
          optimize: true

collections:
- name: "blog"
  label: "Blog"
  folder: "content/blog"
  path: "{{slug}}/index"
  create: true
  extension: "md"
  format: "yaml-frontmatter"
  media_folder: ''
  public_folder: ''
  fields:
  - label: "Title"
    name: "title"
    widget: "string"
  - label: "Date"
    name: "date"
    widget: "datetime"
    date_format: "YYYY-MM-DD"
    time_format: false
    format: "YYYY-MM-DD"
  - label: "Description"
    name: "description"
    widget: "text"
    required: false
  - label: "Tags"
    name: "tags"
    widget: "list"
    required: false
  - label: "Body"
    name: "body"
    widget: "markdown"
- name: "pages"
  label: "Pages"
  files:
  - label: "Homepage"
    name: "homepage"
    file: "content/_index.md"
    fields:
    - label: "Title"
      name: title
      widget: string
    - label: "Body"
      name: body
      widget: markdown
