name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Install Markdown Linter (mdl)
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev
          sudo gem install mdl

      - name: Lint Markdown (optional)
        run: mdl content/

      - name: Build Hugo Site
        run: |
          hugo --minify

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy using SCP and sudo
        run: |
          tar -czf site.tar.gz -C public .
          ls -lha
          scp -O -P 22822 -i ~/.ssh/id_rsa site.tar.gz keefeere@ssh.keefeere.me:site.tar.gz
          
