name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Install Markdown Linter (mdl)
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev
          sudo gem install mdl

      - name: Lint Markdown (optional)
        run: mdl content/

      - name: Build Hugo Site
        run: |
          hugo --minify
          ls public/

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" --delete public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/hugo-site
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo mv /tmp/hugo-site/* ${{ secrets.SSH_TARGET_DIR }} && sudo chown -R root:root ${{ secrets.SSH_TARGET_DIR }}"
