name: Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
         submodules: 'true'

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' #TODO pin version
          extended: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Prettier and markdownlint-cli2
        run: npm install -g prettier markdownlint-cli2

      - name: Run Prettier (auto-format)
        run: prettier --write "content/**/*.md"

      - name: Commit Prettier fixes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git diff --quiet || (git commit -am "fix: autoformat markdown via prettier" && git push)

      - name: Run markdownlint-cli2
        run: markdownlint-cli2 "content/**/*.md"

      - name: Clean public dir
        run: rm -rf public/      
        
      - name: Build Hugo Site
        run: |
          hugo --minify
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy using SCP and sudo
        run: |
          tar -czf site.tar.gz -C public .
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo rm -rf ${{ secrets.SSH_TARGET_DIR }}/*"
          scp -O -i ~/.ssh/id_rsa -P ${{ secrets.SSH_PORT }} site.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:site.tar.gz
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo tar -xzf /volume1/homes/${{ secrets.SSH_USER }}/site.tar.gz -C ${{ secrets.SSH_TARGET_DIR }} && rm /volume1/homes/${{ secrets.SSH_USER }}/site.tar.gz"
